language:
  'javascript'
node_js:
  - "6"
before_script:
  - yarn
script:
  - npm dll
  - npm webpack
notifications:
  webhooks:
    'https://hook.bearychat.com/=bw8UF/travis/a41f37fe322a38c11ecb7945d976d007'
